export const Developers = [
  "HTML & CSS Developer ",
  "JavaScript Developer",
  "TypeScript Developer",
  "PHP Developer ",
  "WordPress Developer",
  "React Developer",
  "NodeJS Developer",
  "Azure DevOps ",
  "MYSQL / NOSQL ",
  "Java Developer",
  "Video Editor",
  "Bibliophile",
]
export const Projects = [
  {
    title: "PortFolio",
    shortDesc: "10",
    Desc: "Description of the title",
    Link: "#",
    TechStack: ["React (TS)", "TypeScript", "Tailwind"],
    Features: [
      "feature 1",
      "feature 1",
      "feature 1",
      "feature 1",
      "feature 1",
      "feature 1",
    ],
    image: "/assets/portfolio.png",
  },
  {
    title: "Emperia",
    shortDesc: "10",
    Desc: "Description of the title",
    Link: "link for the title",
    TechStack: ["React (JS)", "MongoDB", "Express.js", "NodeJS"],
    Features: [
      "feature 1",
      "feature 1",
      "feature 1",
      "feature 1",
      "feature 1",
      "feature 1",
    ],
    image: "/assets/Emperia.png",
  },
  {
    title: "Megane",
    shortDesc: "10",
    Desc: "Description of the title",
    Link: "link for the title",
    TechStack: ["React (TS)", "SQLite", "PHP"],
    Features: [
      "feature 1",
      "feature 1",
      "feature 1",
      "feature 1",
      "feature 1",
      "feature 1",
    ],
    image: "/assets/portFolio",
  },
]
